image: 'calebacosta/rabbitmq_elixir:python-alpine'

services:
  - postgres:9.6

variables:
  POSTGRES_DB: 'postgres'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - rabbitmq-server -detached
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.clean --all
  - mix deps.get --only test
  - mix deps.get
  - pip install pydriller==2.1 erlport==0.6
stages:
  - build
  - quality
  - release

compile:
  stage: build
  script:
    - mix compile --warnings-as-errors
  cache:
    key: 'compile'
    paths:
      - '_build'
      - 'deps'

static_analysis:
  stage: quality
  script:
    - mix credo -a
    - mix format --check-formatted
  cache:
    key: 'compile'
    paths:
      - '_build'
      - 'deps'

test:
  stage: quality
  variables:
    MIX_ENV: 'test'
  script:
    - mix compile
    # TODO set coveralls coverage to 80%
    #- mix coveralls
  cache:
    key: 'compile'
    paths:
      - '_build'
      - 'deps'

build_release:
  stage: release
  when: manual
  only:
    - master
    - tags
  variables:
    MIX_ENV: 'prod'
  script:
    - mix release
