alias RepoMinerCore.Repo
alias RepoMinerCore.UserService.User
alias RepoMinerCore.CodeRepoService.Repository
alias RepoMinerCore.CodeRepoService.Status
alias RepoMinerCore.CodeRepoService.CommitsDensity
alias RepoMinerCore.CodeRepoService.Branches
alias RepoMinerCore.CodeRepoService.UserCommits
alias RepoMinerCore.CodeRepoService.UserCommitsService
alias RepoMinerCore.CodeRepoService.RepositoryService
alias RepoMinerCore.CodeRepoService.CommitsDensityService
alias RepoMinerCore.CodeRepoService.BranchesService

alias RepoMinerCore.UserService


