alias RepoMinerCore.Repo
alias RepoMinerCore.UserService.User
alias RepoMinerCore.CodeRepoService.Branches
alias RepoMinerCore.CodeRepoService.Commits
alias RepoMinerCore.CodeRepoService.Repository
alias RepoMinerCore.CodeRepoService.Status

